- pylearn2/datasets/tests/__init__.py
- pylearn2/datasets/tests/test_adult.py
- pylearn2/datasets/tests/test_mnist.py
- pylearn2/datasets/tests/test_mnist_rotated.py
Added two tests based on previous pull request #666 
Kelvin
> Added unit tests for rotated mnist and adult

- pylearn2/datasets/adult.py
- pylearn2/datasets/tests/test_adult.py
- pylearn2/datasets/tests/test_avicenna.py
- pylearn2/datasets/tests/test_cifar100.py
- pylearn2/datasets/tests/test_cos_dataset.py
- pylearn2/datasets/tests/test_hepatitis.py
- pylearn2/datasets/tests/test_iris.py
- pylearn2/datasets/tests/test_ocr.py
Seems that David Kruger has already finished dealing with the following 5 datasets tests in ticket https://github.com/lisa-lab/pylearn2/pull/666:
* iris
* ocr
* hepatitis
* avicenna
* cifar100
So here we just copy his codes into this PR and check if that will work first.
We'll find a way to deal with cosdataset in future commits of this PR.
> Added more test codes from David Kruger, dealing with cosdataset now.

- pylearn2/sandbox/rnn/space/__init__.py
- pylearn2/sandbox/rnn/utils/iteration.py
creating masks was done after swapping axes, which gave wrong masks
> fixing bug with creating masks

- pylearn2/costs/ebm_estimation.py
- pylearn2/devtools/tests/test_format.py
- pylearn2/energy_functions/tests/test_rbm_energy.py
- pylearn2/sandbox/cuda_convnet/debug.py
- pylearn2/scripts/datasets/make_cifar100_gcn_whitened.py
- pylearn2/scripts/datasets/make_cifar100_patches.py
- pylearn2/scripts/datasets/make_cifar100_patches_8x8.py
- pylearn2/scripts/datasets/make_cifar100_whitened.py
- pylearn2/scripts/datasets/make_cifar10_gcn_whitened.py
- pylearn2/scripts/datasets/make_cifar10_whitened.py
- pylearn2/scripts/datasets/make_stl10_patches.py
- pylearn2/scripts/datasets/make_stl10_patches_8x8.py
- pylearn2/scripts/datasets/make_stl10_whitened.py
- pylearn2/scripts/icml_2013_wrepl/multimodal/make_wordlist.py
- pylearn2/scripts/lcc_tangents/make_dataset.py
Fix files that do work on import instead of only if __name__ == __main__
> Fix files that do work on import instead of only if __name__ == __main__, #822, by saizheng

- pylearn2/devtools/tests/test_format.py
- pylearn2/models/tests/test_mlp.py
I need some feedback on the following tests for FlattenerLayer:
1) I can't get the fprop to work on my toy example, what is wrong?
2) Do we need more tests on the "inner" FlattenerLayer to see if its other methods (e.g. get_monitoring_channels, get_weights, cost...) agree with what they are truly supposed to be? @dwf
> Initial work on issue 921: creating tests for FlattenerLayer.

- pylearn2/datasets/retina.py
- pylearn2/datasets/tests/test_adult.py
- pylearn2/datasets/tests/test_retina.py
@memimo Initialial tests for retina pending comment.
> Add unit tests

- pylearn2/datasets/vector_spaces_dataset.py
- pylearn2/sandbox/nlp/models/__init__.py
- pylearn2/sandbox/nlp/models/mlp.py
- pylearn2/sandbox/nlp/models/tests/composite.yaml
- pylearn2/sandbox/nlp/models/tests/test_mlp.py
- pylearn2/utils/data_specs.py
- pylearn2/utils/iteration.py
To be used in multi-task learning.
> Modify projection layer (sandbox) to handle composite space

- doc/index.txt
Added some descriptions for optional dependencies.
> Updated dependencies documentation

- pylearn2/datasets/csv_dataset.py
Delimiter should be of datatype string and not boolean!
> Updated CSVDataset docstring

- pylearn2/costs/gated_autoencoder.py
- pylearn2/models/gated_autoencoder.py
- pylearn2/scripts/tutorials/gae_demo/README
- pylearn2/scripts/tutorials/gae_demo/__init__.py
- pylearn2/scripts/tutorials/gae_demo/gae_random.yaml
- pylearn2/scripts/tutorials/gae_demo/make_random_dataset.py
- pylearn2/scripts/tutorials/gae_demo/test_gae.py
- pylearn2/scripts/tutorials/gae_demo/train_gae.ipynb
Hi again (sorry for the delay) I corrected my previous pull-request, now the gated-autoencoder uses CompositeSpace with Conv2DSpace or VectorSpace with the VectorSpacesDataset. Let me know what you think.
> Added gated-autoencoder and an example

- pylearn2/models/mlp.py
- pylearn2/models/tests/test_mlp.py
- pylearn2/space/__init__.py
- pylearn2/space/tests/test_space.py
This is motivated by the following problem:
FlattenerLayers interact with their raw_layers when costs are called from them and when monitoring channels are requested. Both of these things generally do not want the FlattenerLayer output, but rather the output of the layers in the CompositeLayer the FlattenerLayer wraps. This can't be done with another format_as since this adds more theano ops and then the costs and monitoring channels can't get the actual results of fprop easily.
Fixes problems referenced here:
https://github.com/lisa-lab/pylearn2/issues/1301
and might help:
https://github.com/lisa-lab/pylearn2/pull/1290
> Implement undo_format_as fixes #1301

- pylearn2/testing/datasets.py
- pylearn2/testing/tests/test_datasets.py
> Update arange dataset

- pylearn2/models/mlp.py
- pylearn2/models/tests/test_mlp.py
Added test failed before change.
https://groups.google.com/forum/#!topic/pylearn-dev/RxGwmSvuqtg
> max_pool works with anon variable

- pylearn2/models/mlp.py
- pylearn2/models/tests/test_mlp.py
Test failed before the line was removed. The correct check is already done in CompositeLayer.set_input_space() here:
https://github.com/lisa-lab/pylearn2/blob/e9338af5050b7dda2fa87204d4eee89a3ed8fbdb/pylearn2/models/mlp.py#L4165
> removed bad check, fixes #1338

- pylearn2/datasets/csv_dataset.py
add kwargs to __init__() of CSVData, so that this class could use features of it's parent class, DenseDesignMatrix.
For example, the view_converter of  DenseDesignMatrix could not be initialized without this change.
> add kwargs to __init__ of CSVData

- pylearn2/devtools/tests/test_format.py
> Dewhitelist iteration.py from format checks.

- pylearn2/utils/data_specs.py
> More general check in data_specs

- doc/internal/pull_request_checklist.txt
- pylearn2/scripts/papers/maxout/compute_test_err.py
First commit fixes #1354.
Second commit fixes #1157
> Small fixes

- pylearn2/datasets/tests/test_zca_dataset.py
> Added test for ZCA_Dataset.

- pylearn2/datasets/csv_dataset.py
Rebased + added some features: https://github.com/lisa-lab/pylearn2/pull/1072
> generalization of CSV dataset + shuffle feature

- doc/library/index.txt
costs were repeated two times in the documentation
> removed double costs in documentation

- pylearn2/scripts/train.py
- pylearn2/train_extensions/plots.py
Plotting extension : create png files containing plots for chosen monitoring channels.
> Add plotting extension

- pylearn2/sandbox/cuda_convnet/conv_util.cuh
- pylearn2/sandbox/cuda_convnet/cudaconv2.cuh
- pylearn2/sandbox/cuda_convnet/nvmatrix.cuh
- pylearn2/sandbox/cuda_convnet/weight_acts.cuh
This is for an upcoming change in theano.
> Make sure the required symbols are visible.

- pylearn2/costs/tests/test_term_1_0_l1_penalty.py
Changed the integer division to integer / float
Changed the L1WeightDecay(tuple) to L1WeightDecay(dict)
> Updated test based on Pascal Lamblin's comments

- pylearn2/model_extensions/norm_constraint.py
- pylearn2/model_extensions/tests/test_norm_constraint.py
The unit test was updating a parameter to its current value so it didn't catch the bug. I updated the test to actually propose modifying the parameter.
> fix bug in norm constraint

- pylearn2/linear/cudnn2d.py
- pylearn2/linear/tests/test_cudnn.py
- pylearn2/models/mlp.py
This is a merge of an old work by @ballasn.
> Use cudnn when possible instead of conv2d

- pylearn2/models/mlp.py
@jstaker7 thanks for pointing this out
@lamblin it should be possible to merge this right away
> Fix import from pylearn2.linear instead of linear

- pylearn2/datasets/dense_design_matrix.py
- pylearn2/datasets/tests/test_dense_design_matrix.py
> Added X_labels and y_labels to DenseDesignMatrixPyTables constructor.

- pylearn2/models/autoencoder.py
- pylearn2/models/tests/test_autoencoder.py
I deleted previous pull request and open a new request.
I tested it on the latest code.
> Add StackedDenoisingAutoencoder

- pylearn2/models/mlp.py
@lamblin In this case the parent class doesn't necessarily have the parameters so I copied the documentation from other sources.
> Cleaned up documentation.

- pylearn2/testing/datasets.py
- pylearn2/train_extensions/tests/test_wmape_channel.py
- pylearn2/train_extensions/wmape_channel.py
This is just a rebase and squash of commits in #1479 to avoid the merge commits.
I've already reviewed and approved it.
> Rebase and squash of Wmape PR

- pylearn2/training_algorithms/learning_rule.py
- pylearn2/training_algorithms/tests/test_learning_rule.py
- pylearn2/training_algorithms/tests/test_sgd.py
This new pull request takes into consideration comments by @lamblin  and @alexjc on the previous iteration.
> AdaGrad accepts zero-filled params - fixes #1499, #1496

- pylearn2/scripts/jobman/experiment.py
- pylearn2/scripts/tutorials/convolutional_network/conv.conf
Added default results extractor function.
> Added jobman conf for conv tutorial.

- pylearn2/datasets/tests/test_zca_dataset.py
This should avoid the problem encountered with Travis on #1519.
> Make ZCA test use fixed seed

- pylearn2/devtools/nan_guard.py
- pylearn2/devtools/tests/test_nan_guard.py
- pylearn2/train_extensions/tests/test_roc_auc.py
Fixes #1172.
Already reviewed, merge at will when Travis passes.
> Rebase of #1486

- .travis.yml
- README.rst
- doc/index.txt
I think we should warn people about this.
> Tell that Pylearn2 have no more developer.
