- .travis.sh
- .travis.yml
Small change, but should see significant improvement in Travis CI runtimes. MKL shaves off about half an hour of the total runtime, and on top of that the builds should start sooner.
Fixes #1367.
> Enable Travis container environment

- pylearn2/models/mlp.py
- pylearn2/models/tests/test_mlp.py
Using `binary_target_dim` rather than 1 will result in these errors:
````
ValueError: Input dimension mis-match. (input[0].shape[0] = 1968, input[2].shape[0] = 123)
Apply node that caused the error: Elemwise{Composite{[add(i0, mul(i1, i2))]}}[(0, 2)](Flatten{1}.0, TensorConstant{(1,) of 60000}, ARange.0)
Inputs types: [TensorType(int64, vector), TensorType(int64, (True,)), TensorType(int64, vector)]
Inputs shapes: [(1968,), (1,), (123,)]
Inputs strides: [(8,), (8,), (8,)]
Inputs scalar values: ['not scalar', array([60000]), 'not scalar']
````
and
````
ValueError: total size of new array must be unchanged
Apply node that caused the error: Reshape{1}(monitoring_targets, MakeVector.0)
Inputs types: [TensorType(int64, matrix), TensorType(int64, vector)]
Inputs shapes: [(10, 16), (1,)]
Inputs …
```
> fix Reshape error and "Input dimension mis-match" when using Softmax layer with binary_target_dim > 1

- pylearn2/utils/iteration.py
A deprecated code used to create two different init_fn and fn. 
When it was deleted a part of it was not deleted. 
If init_fn is None, fn is always None --> the else branch is never used.
> Fix old deprecated code that can never be executed

- pylearn2/utils/string_utils.py
- pylearn2/utils/tests/test_string_utils.py
In Python 3, comparison of `float` and `str` raises TypeError. In this commit, I added conditionals for checking types.
> Fixed number_aware_alphabetical_cmp

- pylearn2/expr/basic.py
- pylearn2/expr/tests/test_basic.py
log_sum_exp was unecessarily specified in terms of log A. This rephrases it to just be A, and adds some tests.
> log_sum_exp tests and interface cleanup

- pylearn2/utils/image.py
If pylearn2 is run in an environment without GUI (such as Ubuntu 14.04 Server), matplotlib import crashes. See https://github.com/lisa-lab/pylearn2/issues/1391
> Handle TypeError in matplotlib import

- pylearn2/datasets/preprocessing.py
Methods and variables in ExamplewiseAddScaleTransform share the same names (_add, _multiply).
> Naming issue

- pylearn2/scripts/datasets/download_svhn.sh
[chg] Added ./pylearn2/scripts/datasets/download_svhn.sh script for SVHN dataset download to the $PYLEARN2_DATA_PATH/SVHN/format2 directory. The script is closely based on download_cifar10.sh, but it uses a verbose wget or curl.
> Added shell script to download the SVHN dataset

- doc/internal/data_specs.txt
This removes extra unwanted parentheses.
> Replace :meth: by py:method:: in documentation.

- pylearn2/packaged_dependencies/theano_linear/unshared_conv/localdot.py
Now matplotlib import here exactly mirrors that from https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/utils/image.py, which is another fix for https://github.com/lisa-lab/pylearn2/issues/1391.
> Fixed matplotlib import

- pylearn2/devtools/tests/test_format.py
- pylearn2/training_algorithms/sgd.py
- pylearn2/training_algorithms/tests/test_sgd.py
When using a large training set, it can take a long time for the first epoch to complete and display the first monitor update. I wanted to see that progress was being made during the epoch, so I wrote an SGD callback to do this using the method suggested by Ian here https://groups.google.com/forum/#!topic/pylearn-users/Mz1_1yqSYeA
This can be used to print simple one-line updates giving the current epoch and batch at a specified rate, and/or to print monitor updates within epochs at a specified rate. 
I also made the file consistent with PEP8.
> EpochMonitor callback for monitoring progress within epochs

- pylearn2/datasets/preprocessing.py
- pylearn2/datasets/tests/test_preprocessing.py
- pylearn2/datasets/zca_dataset.py
inv_P and P are used in zca_dataset and are accessed
directly. It also makes the assumption that a ZCA object has  
those attributes after initialization, but it's not true for old 
pickled ZCA. 
This pull request adds a getter/setter interface
to access them and also get rids of the assumption that
inv_P_ or P_ is an attribute of t.
It completes a fix made in #833
> Implements setter and getter for inv_P and P

- pylearn2/models/mlp.py
- pylearn2/models/tests/test_mlp.py
Equivalent to pylearn2.mlp.max_pool() but with cuDNN pooling.
In a 5 layer mlp with 2 to 3 layers of convolution and pooling, the version with cuDNN was 25-40% faster.
Note that since the implementation of cudnn mean pooling is not the same between versions and theano supports multiple versions, it's not easy to support mean pooling with cudnn and get consistent results. Mabye once cudnn stabilizes it can be added more easily.
> Use cudnn max pooling when possible

- pylearn2/scripts/plot_monitor.py
Sorry this took so long.  I had a lot of trouble getting the vertical alignment to work properly.  Although line 302 seems to align everything properly, I had to play around quite a bit to come up with 1-6*pad_height/total_height.  I'm fairly certain that this is not the best solution.
The pictures that it outputs are reasonably nice, but the dynamic display is still cutoff, and I'm not sure how to fix this without calling a package to add scrollbars.
> plot_monitor.py

- pylearn2/sandbox/rnn/utils/iteration.py
`batch` might have a shape like (batch_size, sequence_length, feature, feature, ...).
The original code uses `np.transpose(batch, (1, 0, 2))` to swap the 0th and the 1st axes.
But using `np.swapaxis(batch, 0, 1)` is better than `np.transpose`.
Currently this is not a problem since the possible dimension of `batch` is only 3.
But in the future, if one want to use the space `SequenceDataSpace(Conv2DSpace)` (currently this is not allowed to use with RNN), the shape of `batch` will be (batch_size, sequence_length, row, col, channel) which dimension is 5 and `np.transpose(batch, (1, 0, 2))` will not match its shape.
> fix SequenceDatasetIterator's small bug

- pylearn2/sandbox/rnn/models/rnn.py
The docstrings of `LSTM` and `GRU` about `output` parameter are incorrect. 
Actual parameter name that they expect is `indices` as `Recurrent`.
The docstring of `Recurrent` class has been correctly fixed at [this commit](https://github.com/lisa-lab/pylearn2/commit/df3a0c54af23431042c30063de4615b916cf6c89#diff-99dd2c7f58dcebb88cf63a031a0a017aR37). 
But at that time the `LSTM`'s docstring was left incorrect.
After that, the `GRU`'s docstring is copied from `LSTM`'s one at [this commit](https://github.com/lisa-lab/pylearn2/commit/62bc2cc3689196cbe38346bf389188a604f8b44e#diff-99dd2c7f58dcebb88cf63a031a0a017aR620).
> fix incorrect parameter name in docstrings of LSTM and GRU

- pylearn2/utils/iteration.py
We'll put it back when more datasets have been ported to the new interface.
> Remove deprecation warning for FiniteDatasetIterator

- pylearn2/sandbox/rnn/models/rnn.py
The super class of `RNN` is `MLP`. The order of parameter list of the constructor of `MLP` is:
```python
def __init__(self, layers, batch_size=None, input_space=None,
input_source='features', target_source='targets',
nvis=None, seed=None, layer_name=None, monitor_targets=True,
**kwargs):
```
But in the constructor of `RNN`, `super`'s constructor is called with arguments like:
```python
super(RNN, self).__init__(layers, batch_size, input_space,
input_source, nvis, seed, layer_name,
**kwargs)
```
, which means `target_source=nvis`. 
This PR  fixes it by keyword arguments.
> fix inconsistency of arguments in the constructor of RNN

- pylearn2/linear/local_c01b.py
- pylearn2/models/maxout.py
missing constructor in MaxoutLocalC01B
only show warning if partial_sum is used
```bash
$ THEANO_FLAGS='device=cpu' theano-nose pylearn2/linear/local_c01b.py
----------------------------------------------------------------------
Ran 0 tests in 0.000s
OK
$ THEANO_FLAGS='device=cpu' theano-nose pylearn2/models/maxout.py
----------------------------------------------------------------------
Ran 0 tests in 0.000s
OK
```
> fixes #1445

- pylearn2/tests/test_monitor.py
- pylearn2/training_algorithms/tests/test_sgd.py
- pylearn2/utils/iteration.py
- pylearn2/utils/tests/test_iteration.py
This iterator is used for datasets with sequential data (e.g. list of words). It returns a list of indices such that sequences within a minibatch which will have the same lengths.
Therefore, it might return minibatches with different sizes, but it usually gives a speedup of 20% for processing sequential data.
> Adding even sequences subset iterator

- pylearn2/training_algorithms/sgd.py
When using PyLearn2 from another python library, I've found it would be easier to have specific exceptions to deal with common problems during training (e.g. NaN in SGD).
This PR will raise a `RuntimeError` instead of an exception when training results in NaN. This makes it easier to catch problems and fits a little better with the official Python exception classifications.
> Raising a `RuntimeError` when NaN is found during training

- pylearn2/format/target_format.py
- pylearn2/format/tests/test_target_format.py
Simple fix: symbolic expressions for OneHotFormatter currently default to float32 (the formatter's dtype isn't passed on).
Thanks for the great library!
> OneHotFormatter: include dtype in symbolic expression

- pylearn2/models/mlp.py
This fixes a bug where LinearGaussian overrides `cost` but not `cost_matrix`. This means that the value you get from `cost` is not consistent with the value you get from `cost_from_cost_matrix`.
> LinearGaussian.cost_matrix

- pylearn2/space/tests/test_space.py
Theano recently introduced float16 as a scalar dtype, but not
everything supports it. In particular SparseType does not.
This PR should fix the Travis tests that are currently failing.
> Skip tests for VectorSpace(sparse, float16).

- pylearn2/scripts/papers/maxout/cifar10.yaml
- pylearn2/scripts/papers/maxout/cifar10_no_aug.yaml
- pylearn2/scripts/papers/maxout/cifar10_no_aug_valid.yaml
- pylearn2/scripts/papers/maxout/cifar10_old_small.yaml
- pylearn2/scripts/papers/maxout/cifar10_valid.yaml
- pylearn2/scripts/papers/maxout/mnist.yaml
- pylearn2/scripts/papers/maxout/svhn.yaml
- pylearn2/scripts/papers/maxout/svhn2.yaml
- changed models to not require fixed batch, remove use of forced even iterators
- fix padding size in cifar scripts with data augmentation
This should address the problems reported in https://groups.google.com/d/topic/pylearn-dev/geKKzmQ1QbM/discussion
> Fix yaml files in scripts/papers/maxout

- pylearn2/cross_validation/__init__.py
- pylearn2/cross_validation/blocks.py
- pylearn2/cross_validation/dataset_iterators.py
- pylearn2/cross_validation/mlp.py
- pylearn2/cross_validation/subset_iterators.py
- pylearn2/cross_validation/train_cv_extensions.py
- pylearn2/datasets/hdf5_deprecated.py
- pylearn2/scripts/print_monitor_cv.py
- pylearn2/train_extensions/roc_auc.py
I am no longer an active developer of pylearn2 and would like to remove my name as a maintainer of these files.
> Remove obsolete __maintain__ statements

- pylearn2/models/mlp.py
- pylearn2/sandbox/rnn/models/tests/test_rnn.py
This was seemingly causing trouble for some layers.
> Remove RNNWrapper as metaclass for MLP

- pylearn2/datasets/dense_design_matrix.py
- pylearn2/datasets/svhn.py
- pylearn2/devtools/tests/test_format.py
- pylearn2/scripts/datasets/make_svhn_pytables.py
* [**fix**] split_train_valid method in SVHN class is expected to return two tuples, each with two values. But it was returning 4 values. This was
wrongly introduced during commit af07b6cc076942ef4f80c84ec7c7148afb3999ad ("remove one_hot, first try...")
* [**fix**] Added support to specify y_labels in DenseDesignMatrixPyTables constructor.This should have been done as part of the following commits af07b6cc076942ef4f80c84ec7c7148afb3999ad ("remove one_hot, first try...") d6050106f137147ba976e472748ad77273218b55 ("Modified all super() params...")
* [**fix**] Table shape for y (the labels) is now set to [sizes[which_set], 1].
Before it was being wrongly set to [sizes[which_set], 10]. Also y
labels for SVHN now range from [0,9], similar to the MNIST dataset
labels. These changes should have …
> Bugfixes in SVHN and DenseDesignMatrixPyTables

- pylearn2/datasets/svhn.py
Move assertions at a point they would be able to detect that.
Fixes #1532 (what is remaining of it).
> Load correct targets when split is 'train_all'

- pylearn2/models/mlp.py
- pylearn2/scripts/icml_2013_wrepl/multimodal/extract_kmeans_features.py
The module theano.tensor.signal.downsample was removed in Theano, and downsample.max_pool_2d was moved to pool.pool_2d.
https://github.com/Theano/Theano/commit/1960ddab6cb681ab75f714f0d0215a0e725c9ef3
https://github.com/Theano/Theano/commit/372939b1512eadf32bfe3c3aa38b3e4faf9dd792
> Fix broken imports of downsample.max_pool_2d

- pylearn2/sandbox/cuda_convnet/base_acts.py
- pylearn2/sandbox/cuda_convnet/pool.py
- pylearn2/sandbox/cuda_convnet/probabilistic_max_pooling.py
- pylearn2/sandbox/cuda_convnet/stochastic_pool.py
The cuda-convnet wrapper uses `make_thunk` to check if cuda-convnet is available. https://github.com/Theano/Theano/pull/5073 changed the `make_thunk` signature to include an `impl` parameter. This PR changes all `make_thunk` calls to pass on `*args` and `**kwargs` so it is compatible to all versions of Theano. (Theano also has a `prepare_node` method which would be suitable for this check, but I'm not sure if this would work with older Theano versions then.)
> Make cuda-convnet wrapper compatible to recent Theano

- pylearn2/scripts/datasets/make_cifar100_whitened.py
Changed and fixed the wrong import `from pylearn2.utils import string` to its correct form of `from pylearn2.utils import string_utils as string`
> fixed the "ImportError: cannot import name string"
